### PR TITLE
Implement option to run local linter

### PR DESCRIPTION
**Pull request by jpreese**
For #6 

I just started toying around with this extension and this was the first thing I noticed. We use a local installation for our linting, and I'd like to avoid a global installation if possible.

### CODE REVIEW

**Comment by jwldnr** [comment]
Good job @jpreese I'll have a look at this today!

**Comment by jpreese** [comment]
Awesome! Let me know if you'd like any changes made.

**Comment by jwldnr** [comment]
I've gone ahead and merged this with the master branch, but made some minor changes. You can see them in this commit: 2d3c0a3c416e2992dc564ca4fd06e30a5b6244a9

Thank you for your contribution @jpreese !

**Comment by sgordon3** [comment]
Thank you both. I think that's the world's fastest turn around for a feature request. I guess it helps that you were already working in it!

**Pull request merged**
