### PR TITLE
Add TypeScript React Support

### LINKED ISSUE #57: Add Support for TypeScript JSX files (TypeScript React) (.tsx)
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.100

### Description
Add support for TypeScript React files (.tsx)

### Steps to recreate
N/A

### Current behavior
Currently you can enable .jsx and .ts files, but TypeScript JSX files, i.e. TypeScript React files are not linted in Visual Studio.

### Expected behavior
This would require the correct plugins for eslint to work, but on your side should just be adding the file extension. At least it appears that way from #55 .

I'm happy to contribute to a fix if you would prefer that. Just let me know. 

Thanks!

### PR DESCRIPTION
**Pull request by mklosterboer**
* Add '.tsx' to tagger
* Add option to GeneralOptions
* Add tests for '.tsx' extension
* Update CHANGELOG
* Update README

Closes #57

### CODE REVIEW

**Comment by jwldnr** [comment]
Looks good @mklosterboer! 
However I'm currently at work where I have no ability to test this change. I'll have to do it this afternoon. 
I'll let you know once I've released this new change to the Visual Studio Marketplace! 

Thanks for your contribution 😸

**Comment by mklosterboer** [comment]
@jwldnr 
No problem!
Thanks for being open to changes and responding quickly!

**Comment by jwldnr** [comment]
Changes work exactly as you thought they would. Good work @mklosterboer! I'll go ahead and release this to the Visual Studio Marketplace. I'll post back here with the new version number shortly. 👍

**Comment by jwldnr** [comment]
Version `1.1.104` will soon be available! Again, thanks for your contribution @mklosterboer

**Comment by mklosterboer** [comment]
Thanks again for making it painless. I was not anticipating resolving this issue in 24 hours. Thanks @jwldnr!

**Pull request merged**
